### PR TITLE
Revert "avoid allocating ipiv when not pivoting"

### PR DESCRIPTION
**Pull request by YingboMa**
Reverts JuliaLinearAlgebra/RecursiveFactorization.jl#60

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Bump

**Comment by chriselrod** [comment]
We'll want to not allocate ipiv when we finish implementing butterfly.

**Comment by chriselrod** [comment]
Also, what is the error?
I can't imagine that allocating and actually indexing into an `ipiv` vector when not using it actually fixes anything.

**Comment by YingboMa** [comment]
It errors because of the dispatch parameters https://github.com/JuliaLinearAlgebra/RecursiveFactorization.jl/commit/659b99b42ce02bf49e2e9f90b0225cc77b52810e#diff-220df237e6709852877ddd6ec677b63452b162dcac21569789f423fc2774ff7dR41

**Comment by jebej** [comment]
Fixes #67. It would be good to add testing on julia 1.6 to catch things like that.

**Pull request merged**
